application: neuronism2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# CSS
- url: /css
  static_dir: css

# HTML
- url: /static
  static_dir: static_html

- url: /admin.*
  script: admin.app
  login: admin

- url: /.*
  script: main.app
  login: required
